### ISSUE TITLE
like and dislike are only 2 inputs supported by raccoon?

### ISSUE THREAD

**Issue by projectxmaker** [guymorita/recommendationRaccoon#24]
Hi,

I checked ReadMe and found that there are only 2 input types: Like and Dislike for inputting data to raccoon.

What could I do if my app would like to input with other actions such as Share, Vote/Rate?

Regards,

**Comment by guymorita** [comment]
How would you like them to be incorporated? Likes and dislikes are
essentially votes. The algo is based on matching sets of like/dislike lists.
