### ISSUE TITLE
Raccoon returns advises only for last set

### ISSUE THREAD

**Issue by cajoy** [guymorita/recommendationRaccoon#25]
lib/algorithms.js line 176

```
            client.sunionstore(tempSet, set, function(err){
              callback();
            });
```

suinonstore overrides tempSet on each call instead of appending new items.

**Comment by guymorita** [comment]
can you make a PR? thanks :)

**Comment by guymorita** [comment]
@cajoy Yeah. I think there is a bug here. I think the async.each can be removed.

**Comment by guymorita** [comment]
@cajoy Yep you're right. Fixed it here. Thanks for pointing that out! https://github.com/guymorita/recommendationRaccoon/commit/36374ab48397d3b24ce05450f932746cb7948eb8
