### ISSUE TITLE
updateRecommendations should be optional

### ISSUE THREAD

**Issue by cajoy** [guymorita/recommendationRaccoon#26]
Let's say I added 20 items in loop call. The system is re-calculate rating on each addition.

Should be available option to update ration only after all items has been added.

**Comment by guymorita** [comment]
Awww, very true. Yeah that actually gets really annoying. You could build in optional boolean into the like/dislike call that would make it not re-calculate the recommendations. I sense a pull request ;)

**Comment by guymorita** [comment]
@cajoy Thanks for the fix. I'll be implementing it a bit differently in the coming weeks.

**Comment by guymorita** [comment]
@cajoy https://github.com/guymorita/recommendationRaccoon/commit/34a983613165859f7be78ef5377579711548de5f
