### ISSUE TITLE
Recos based only on own likes/dislikes?

### ISSUE THREAD

**Issue by valnub** [guymorita/recommendationRaccoon#30]
I understood that Racoon takes into account what other users liked when giving recos. Is it possible though to only give recommendations based on what the current user liked, without taking into consideration what other users liked/disliked?

**Comment by guymorita** [comment]
Heyo, we need to still base the recommendations off of something. At the core of the engine is collaborative filtering which means the only factor it's using to compare items is the likes/dislikes of others. Feel free to build a new one based on individual features (depending on the item. e.g. cars might be 0-60, price, leather seats, etc), but that would be an entirely diff engine/product. :) Sounds like it could be a fun project.
