### ISSUE TITLE
How to unlike/undislike

### ISSUE THREAD

**Issue by arthurtalkgoal** [guymorita/recommendationRaccoon#31]
Hi, 

My site has like/dislike functions, it works with raccoon well.

However, user can unlike/undislike (undo everything as if no like/dislike before), how can I do that?

**Comment by guymorita** [comment]
hey @arthurtalkgoal , glad to hear it's working well for you!! ummm nope, there is currently no interface for unliking and undisliking, but that makes total sense. i would say i'd get to it but i'm super super busy with work right now, if you edit input.js and do the exact opposite of all those commands that would probably work

**Comment by guymorita** [comment]
pull request?

**Comment by arthurtalkgoal** [comment]
Cool. I can PR

**Comment by guymorita** [comment]
Input.js as a whole needs to be cleaned up. Thanks man :)

**Comment by arthurtalkgoal** [comment]
Hi @guymorita ,
Can I ask why zincrby is needed in ```liked``` and ```disliked```; doesn't the ```sadd``` add the score?



```
client.sismember([config.className, itemId, 'liked'].join(":"), userId, function(err, results){
      if (results === 0){
        client.zincrby([config.className, 'mostLiked'].join(":"), 1, itemId);
      }
      client.sadd([config.className, userId,'liked'].join(':'), itemId, function(err){
        client.sadd([config.className, itemId, 'liked'].join(':'), userId, function(err){
          updateSequence(userId, itemId, callback);
        });
      });
    });
```

**Comment by rkaneriya** [comment]
Any update on the progress of un-like/un-disliked functionality?

**Comment by guymorita** [comment]
@arthurtalkgoal Hey, I'm working on this project again. The call to zincrby is for the mostliked list. Which is a separate count of which items are most liked.

**Comment by guymorita** [comment]
@arthurtalkgoal @rkaneriya Hey, this is one of the first features I'll be building in the next few weeks.
