### ISSUE TITLE
reccomendFor empty array

### ISSUE THREAD

**Issue by gsmeros** [guymorita/recommendationRaccoon#35]

**Comment by guymorita** [comment]
How many ratings were there? Has user 1 already rated everything?



—

**Comment by gsmeros** [comment]
i am looping a query and insert ratings . if i use then the users ratings and then recommend it works fine! but it seems that I have problems with async because I get out of memory and node keeps running 100%cpu. my code :

connection.query('SELECT * FROM `ratings`', function (error, results, fields) {
    results.forEach(function(user){
      if (user.rating < 3)
        raccoon.disliked(user.userId, user.movieId, function() {});
      else
        raccoon.liked(user.userId, user.movieId, function() {});
    });
connection.end();

if it is a loop , where can I put the recommendFor ?

**Comment by gsmeros** [comment]
I also tried this : 
connection.query('SELECT * FROM `ratings`', function (error, results, fields) {
    async.parallel([
      function(done) {
         console.log("Updating Engine");
         results.forEach(function(user){
            if (user.rating < 3)
                raccoon.disliked(user.userId, user.movieId, function() {});
            else
                raccoon.liked(user.userId, user.movieId, function() {});
         });
         done(null);
      }], function (err) {
      response.send("finished");
    });
  });

**Comment by gsmeros** [comment]
Also the redis server keys * :  
1) "movie:2788:liked"
  2) "movie:3880:disliked"
  3) "movie:1226:liked"
  4) "movie:592:liked"
  5) "movie:3508:liked"
  6) "movie:2353:liked"
  7) "movie:317:liked"

**Comment by gsmeros** [comment]
sorry for the trouble. I manage to fix mostly everything with alternative code. but it seems that my database ( 100.000 ratings from movielens ) is too big to uploaded into redis. It crashes after 13-14k entries

**Comment by guymorita** [comment]
it looks like every set should be able to hold 2^32,
http://redis.io/topics/faq

sure that's it? what was the fix? thanks for keeping me in the loop!

On Tue, Oct 13, 2015 at 10:11 AM, George Smeros <notifications@github.com>
wrote:

> sorry for the trouble. I manage to fix mostly everything with alternative
> code. but it seems that my database ( 100.000 ratings from movielens ) is
> too big to uploaded into redis. It crashes after 13-14k entries
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guymorita/recommendationRaccoon/issues/35#issuecomment-147780650>
> .
>



-- 

*Guy Morita*

*T* 206.240.5846  *l*  *guymorita@gmail.com* <guymorita@gmail.com>

LinkedIn <http://www.linkedin.com/in/guymorita> *l* Github
<https://github.com/guymorita> *l* Developer Blog
<http://guymorita.tumblr.com> *l* Svbtle <http://alchemist.svbtle.com>

**Comment by gsmeros** [comment]
If I use this if statement and then try to recommendFor in the callback it doesnt work. Redis is still storing in the background. So what I did i am just trying to put everything up from my training dataset into redis.(Stops at 13k keys) then with every like/dislike of the user I return the updated recommendset. I think maybe Redis can handle the request but node is crashing while it tries to store. Probably a memory issue in my end , but the macbook I am using has no problems...

**Comment by gsmeros** [comment]
I used a remote server and in a 100.000 ratings table (movie lens) I got 13.8k keys into redis. is this correct ? does this count movieIds only ?

**Comment by joshbedo** [comment]
Same thing happened to me, I simply put code in my test that was displayed in the example. I logged into my redis server and made sure that the keys do exist. Here is the code i have.

```js
var expect = require('chai').expect;
var raccoon = require('raccoon');
raccoon.connect(6379, '192.168.99.100');

describe('bullshit', function() {

  before(function(done) {
    raccoon.flush();
    done();
  });

  before(function(done) {
    raccoon.liked('garyId', 'movieId');
    raccoon.liked('garyId', 'movie2Id');
    raccoon.liked('chrisId', 'movieId');
    done();
  });

  it('should show movie2', function(done) {
    raccoon.recommendFor('chrisId', 10, function(results) {
      console.log(results, 'results');
      expect(true).to.eq(false);
      done();
    })
  });
})
```

**Comment by guymorita** [comment]
@joshbedo I updated the readme to show that the liked /disliked calls are async. They now use promises. So if you call recommendFor before they resolve, you won't get any recommendations.

**Comment by guymorita** [comment]
@gsmeros I'm going to try the Movielens database as well and I'll let you know what the results are!

For every user there are:
liked lists
disliked lists
similarity sets
recommendation sets

For every item there are:
liked lists
disliked lists

Others include:
most liked set
most disliked set
overall score
