### ISSUE TITLE
Same namespace used for both users and items

### ISSUE THREAD

**Issue by gabe-alex** [guymorita/recommendationRaccoon#42]
I just noticed this, and it's surprising that nobody pointed it out before.
This can create some conflicts, especially if numbers are used for user & item IDs.

I will attempt to fix it myself in my existing PR.
Edit: done. #41

**Comment by guymorita** [comment]
@gabe-alex Wow, yeah huge that no one pointed that out. Fixed it in my own. Sorry I didn't see your fix in time. I'm going to be actively working on the project again. Are you still working on it? Thanks for all the work thus far. I'll work on getting some of the fixes in. Take a look at the current master.

**Comment by guymorita** [comment]
Lemme know if you're still interested. Lots of cool features to build.

**Comment by guymorita** [comment]
@gabe-alex All done https://github.com/guymorita/recommendationRaccoon/commit/1e6c0728233c23ace186b91eee8d579d8f243717
