### ISSUE TITLE
Cannot change a rating once added

### ISSUE THREAD

**Issue by gabe-alex** [guymorita/recommendationRaccoon#43]
- disliking something you liked doesn't remove it from the liked list.
- liking something you disliked  doesn't remove it from the disliked list.
- and there's no way to remove a rating.

How is this module even supposed to be used? Am I supposed to re-make the whole redis database every time I want to change it? Because that defeats the point of using redis for its speed...

**Comment by guymorita** [comment]
@gabe-alex Hey, sorry for the late response. This feature makes sense. I'll build it in. No the point is to use a persistent redis store just like any other db.

**Comment by guymorita** [comment]
@gabe-alex https://github.com/guymorita/recommendationRaccoon/commit/c6744653b6753bec02fd35f47200f563c7823f88

**Comment by guymorita** [comment]
What do you mean by remake the whole db? You can host it remotely. And everytime ratings come you decide whether to update recs or not. As for how they update, I'm working on making it more efficient now.
