### ISSUE TITLE
Neglected Library

### ISSUE THREAD

**Issue by ericraio** [guymorita/recommendationRaccoon#44]
Anyone interested in joining me in creating a new organization to house this npm module and be more active?

**Comment by guymorita** [comment]
Hey Eric,

Sounds like a great idea. I'm on the road for the next few months and haven't had the time to give it what it deserves. Feel free to carry the torch.

**Comment by slowmove** [comment]
@ericraio absolutely, moving it over to ES6 and promises would be something I would like to join as well-

**Comment by guymorita** [comment]
Hey Erik / Eric, any other feature requests? I have some time to devote over the next 4-6 weeks.

**Comment by slowmove** [comment]
I think the easiest way to keep it going is to clean up the code up to modern standard to make it easier to clear out bugs and add features later on, but that's of course your decision =)

Please let me know if I can help out contributing.

**Comment by guymorita** [comment]
Yeah that sounds reasonable. Any libraries in particular that are good to model after?

**Comment by slowmove** [comment]
@guymorita I think just a simple refactoring up to ES6 standards including arrow functions, let / const and promises instead of callbacks will be the perfect first baseline to reach 😊

**Comment by guymorita** [comment]
On it :)

**Comment by guymorita** [comment]
@ericraio @slowmove actively working on it again. going to crank out some key features then launch 3.0.
