### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by halileohalilei** [guymorita/recommendationRaccoon#47]
I have a database of 127k entries, each corresponding to a userId and a movieId. I want to add these to raccoon with the raccoon.liked() method when I start my server, but doing that seems to hit the memory limit real fast. Is that normal? The .csv version of this data is not even 10 MB. What sort of data structure is being used in the implementation that it allocates around 1.5 GB for just 100 entries, hitting the memory limit?

**Comment by guymorita** [comment]
@halileohalilei Hey Halil,

Thanks. That seems very possible. I'm going to try to run it with the movielens benchmark to see how it performs. In terms of the data structures being stored.

For every user there are:
liked lists
disliked lists
similarity sets
recommendation sets

For every item there are:
liked lists
disliked lists

Others include:
Most liked set
Most disliked set
Overall score

**Comment by guymorita** [comment]
@halileohalilei working on the memory problem now. there seems to be a leak but i'm having problems installing heapdump because of node-gyp. i'll let you know when i figure it out. also made a repo for benchmarking movielens 100k with raccoon: https://github.com/guymorita/benchmark_raccoon_movielens

**Comment by guymorita** [comment]
@halileohalilei i got it to work on the movielens 100k data set. please see the benchmark repo here. the short solution is to increase the memory allocated to node. i'm still looking into other ways. please check it out here: https://github.com/guymorita/benchmark_raccoon_movielens
