### ISSUE TITLE
ES6 support

### ISSUE THREAD

**Issue by mtzakris** [guymorita/recommendationRaccoon#52]
The latest version throws an error for ES6. Older versions work.
 Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

**Comment by guymorita** [comment]
@mtzakris what version of node are you using? can you upgrade to 6.0+?

**Comment by mtzakris** [comment]
@guymorita you are right my bad. thanks

**Comment by guymorita** [comment]
@mtzakris Great, let me know if anything else comes up
